# -*- coding: utf-8 -*-
"""DINRAJ_MusicGeneration_RNN.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1hv1mrVdEmjbanQ75whmPvjgS0_XeYiFm

# 🎵 RNN Music Generation — Complete Pipeline
### LSTM · GRU · Bidirectional LSTM | TensorFlow/Keras | Google Colab T4

**Project by DINRAJ K DINESH** | Portfolio: dinrajkdinesh.vercel.app

---

## 📋 Notebook Contents
| # | Section | Description |
|---|---------|-------------|
| 1 | GPU Setup | Verify T4 GPU + install deps |
| 2 | Dataset | Load Classical MIDI via music21 corpus |
| 3 | Preprocessing | Parse MIDI → pitch tokens → sequences |
| 4 | Models | LSTM · GRU · BiLSTM architectures |
| 5 | Training | Train all 3 with callbacks + curves |
| 6 | Export | .keras · .h5 · TFLite · JSON+weights · vocab |
| 7 | Download | ZIP everything for web app deployment |
| 8 | Generate | Compose music with temperature sampling |
| 9 | Playback | Render MIDI → audio inside Colab |

> **Runtime:** Set to `T4 GPU` → Runtime → Change Runtime Type → GPU

## ⚙️ Section 1 — GPU Verification & Environment Setup
"""

# ── Verify GPU ───────────────────────────────────────────────────────
import subprocess, sys

gpu_info = subprocess.run(['nvidia-smi'], capture_output=True, text=True)
if 'T4' in gpu_info.stdout:
    print('✅ T4 GPU detected!')
elif 'failed' in gpu_info.stderr.lower() or gpu_info.returncode != 0:
    print('⚠️  No GPU detected. Go to Runtime → Change Runtime Type → GPU')
else:
    print('✅ GPU detected (not T4, but will work):')
print(gpu_info.stdout[:500])

# ── Install all dependencies ─────────────────────────────────────────
!pip install -q music21 pretty_midi matplotlib seaborn
!apt-get install -qq -y musescore3 fluidsynth
!pip install -q pyfluidsynth
print('✅ All dependencies installed')

"""## 📦 Section 2 — Imports & Global Configuration"""

import os, pickle, zipfile, shutil, warnings
import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import seaborn as sns
from collections import Counter
from IPython.display import Audio, display, FileLink

import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers, callbacks, optimizers

import music21
from music21 import corpus, converter, note, chord, stream, instrument
import pretty_midi

warnings.filterwarnings('ignore')
tf.random.set_seed(42)
np.random.seed(42)

print(f'TensorFlow  : {tf.__version__}')
print(f'Keras       : {keras.__version__}')
print(f'music21     : {music21.__version__}')
print(f'NumPy       : {np.__version__}')
print(f'GPU devices : {tf.config.list_physical_devices("GPU")}')

# ── Global Configuration ─────────────────────────────────────────────
# All hyperparameters in one place — easy to tune

CFG = {
    # Vocabulary
    'MIDI_MIN'      : 21,       # A0 — lowest piano key
    'MIDI_MAX'      : 108,      # C8 — highest piano key
    'REST_TOKEN'    : 88,       # silence token index
    'VOCAB_SIZE'    : 89,       # 88 pitches + 1 REST
    'REST_THRESHOLD': 0.5,      # quarter-note gap that triggers REST

    # Sequences
    'SEQ_LEN'       : 32,       # notes fed into LSTM per prediction
    'VAL_SPLIT'     : 0.1,      # 10% validation

    # Model
    'EMBED_DIM'     : 64,       # token embedding size
    'HIDDEN_DIM'    : 256,      # LSTM/GRU hidden units
    'DROPOUT'       : 0.3,

    # Training
    'BATCH_SIZE'    : 128,
    'EPOCHS'        : 50,
    'LR'            : 0.001,
    'PATIENCE'      : 8,        # early stopping patience

    # Generation
    'GEN_LENGTH'    : 200,      # notes to generate
    'TEMPERATURE'   : 0.8,      # 0.5=conservative, 1.0=random, 1.2=creative

    # Paths
    'EXPORT_DIR'    : '/content/music_rnn_export',
    'MIDI_OUT'      : '/content/generated_music.mid',
}

os.makedirs(CFG['EXPORT_DIR'], exist_ok=True)
print('✅ Configuration set:')
for k, v in CFG.items():
    print(f'   {k:20s} = {v}')

"""## 🎹 Section 3 — Dataset Loading

We use **music21's built-in corpus** — no external download needed.
It contains hundreds of Bach chorales, Mozart sonatas, Beethoven pieces, and more.
All parsed directly in Colab.

> 💡 **Want to use your own MIDIs?** Upload them to Colab and set `CUSTOM_MIDI_DIR` below.
"""

# ── Option A: music21 built-in corpus (DEFAULT — no download needed) ──
# ── Option B: Custom MIDI folder — uncomment and set path ─────────────

CUSTOM_MIDI_DIR = None   # e.g. '/content/drive/MyDrive/midi_files'

def get_corpus_paths():
    """Returns list of (path, title) for corpus pieces to use."""
    # Bach chorales: 370+ pieces, clean monophonic/4-part harmony
    bach_paths = corpus.getComposer('bach')
    # Add some Mozart and Beethoven for variety
    try:
        mozart_paths = corpus.getComposer('mozart')[:20]
    except:
        mozart_paths = []
    try:
        schubert_paths = corpus.getComposer('schubert')[:20]
    except:
        schubert_paths = []

    all_paths = list(bach_paths) + list(mozart_paths) + list(schubert_paths)
    print(f'Found {len(all_paths)} corpus pieces')
    print(f'  Bach      : {len(bach_paths)}')
    print(f'  Mozart    : {len(mozart_paths)}')
    print(f'  Schubert  : {len(schubert_paths)}')
    return all_paths

if CUSTOM_MIDI_DIR:
    from glob import glob
    midi_paths = glob(os.path.join(CUSTOM_MIDI_DIR, '**/*.mid'), recursive=True)
    midi_paths += glob(os.path.join(CUSTOM_MIDI_DIR, '**/*.midi'), recursive=True)
    USE_CORPUS = False
    print(f'Using custom MIDI dir: {len(midi_paths)} files found')
else:
    midi_paths = get_corpus_paths()
    USE_CORPUS = True
    print(f'\n✅ Using music21 corpus — {len(midi_paths)} pieces ready')

"""## 🔧 Section 4 — MIDI Preprocessing & Tokenization

**Token Vocabulary (89 tokens):**
- Token `0–87` → MIDI pitches 21–108 (full piano range)
- Token `88` → REST (silence between notes)

**Chord handling:** Take the HIGHEST pitch (preserves melody line)

**REST insertion:** Gap > 0.5 quarter-notes between notes → insert REST token
"""

# ── Token helper functions ───────────────────────────────────────────

def pitch_to_token(midi_pitch):
    """MIDI pitch 21-108 → token 0-87."""
    return int(midi_pitch) - CFG['MIDI_MIN']

def token_to_pitch(token):
    """Token 0-87 → MIDI pitch 21-108."""
    return token + CFG['MIDI_MIN']

def token_to_name(token):
    """Token → human readable note name (e.g. token 39 → 'C4')."""
    if token == CFG['REST_TOKEN']:
        return 'REST'
    midi_pitch = token_to_pitch(token)
    NOTE_NAMES = ['C','C#','D','D#','E','F','F#','G','G#','A','A#','B']
    octave = (midi_pitch // 12) - 1
    name   = NOTE_NAMES[midi_pitch % 12]
    return f'{name}{octave}'

# Sanity check
print('Token mapping sanity check:')
for t in [0, 39, 51, 60, 87, 88]:
    print(f'  Token {t:3d} → {token_to_name(t)}')
assert token_to_name(39) == 'C4', 'Token 39 must be C4 (Middle C)'
print('\n✅ Token mapping correct. Token 39 = C4 (Middle C) confirmed.')

# ── MIDI parser ──────────────────────────────────────────────────────

def parse_score(score_or_path, use_corpus=True):
    """
    Parse a music21 score or MIDI path → list of pitch tokens.

    Steps:
      1. Load score (corpus or file)
      2. Flatten to single stream of events
      3. Extract notes and chords sorted by onset offset
      4. Chords → take highest pitch (melody preservation)
      5. Insert REST tokens for gaps > REST_THRESHOLD
      6. Filter to piano range [MIDI_MIN, MIDI_MAX]

    Returns: list[int] of tokens, or [] if parsing fails.
    """
    try:
        if use_corpus:
            score = corpus.parse(score_or_path)
        else:
            score = converter.parse(score_or_path)
    except Exception as e:
        return []

    try:
        notes_flat = score.flat.notes
    except Exception:
        return []

    extracted = []  # (offset, midi_pitch)

    for element in notes_flat:
        try:
            offset = float(element.offset)
            if isinstance(element, note.Note):
                extracted.append((offset, element.pitch.midi))
            elif isinstance(element, chord.Chord):
                # Take highest pitch = melody note
                top_pitch = max(n.midi for n in element.pitches)
                extracted.append((offset, top_pitch))
        except:
            continue

    if len(extracted) < CFG['SEQ_LEN'] + 5:
        return []

    # Sort by onset time
    extracted.sort(key=lambda x: x[0])

    # Filter to piano range
    extracted = [(o, p) for o, p in extracted
                 if CFG['MIDI_MIN'] <= p <= CFG['MIDI_MAX']]

    if not extracted:
        return []

    # Build token sequence with REST insertion
    tokens = []
    prev_offset = extracted[0][0]

    for offset, pitch in extracted:
        gap = offset - prev_offset
        if gap > CFG['REST_THRESHOLD']:
            tokens.append(CFG['REST_TOKEN'])
        tokens.append(pitch_to_token(pitch))
        prev_offset = offset

    return tokens


# ── Process all corpus pieces ────────────────────────────────────────
print('Parsing MIDI files... (may take 2-3 minutes for Bach corpus)')
print('─' * 60)

all_tokens  = []
skipped     = 0
file_lengths = []

for i, path in enumerate(midi_paths):
    tokens = parse_score(path, use_corpus=USE_CORPUS)
    if len(tokens) < CFG['SEQ_LEN'] + 1:
        skipped += 1
        continue
    all_tokens.extend(tokens)
    file_lengths.append(len(tokens))

    if (i + 1) % 50 == 0:
        print(f'  [{i+1:4d}/{len(midi_paths)}]  tokens so far: {len(all_tokens):,}')

print(f'\n✅ Parsing complete')
print(f'   Files parsed      : {len(midi_paths) - skipped}')
print(f'   Files skipped     : {skipped} (too short / parse error)')
print(f'   Total tokens      : {len(all_tokens):,}')
print(f'   Avg tokens/file   : {np.mean(file_lengths):.0f}')

# Token distribution
tok_counts = Counter(all_tokens)
n_unique   = len(tok_counts)
rest_pct   = 100 * tok_counts[CFG['REST_TOKEN']] / len(all_tokens)
print(f'   Unique tokens     : {n_unique}/89')
print(f'   REST frequency    : {rest_pct:.1f}%')

# ── Visualise token distribution ────────────────────────────────────

fig, axes = plt.subplots(1, 2, figsize=(16, 5))
fig.suptitle('Token Distribution in Dataset', fontsize=14, fontweight='bold')

# Plot 1: Full token histogram
ax = axes[0]
tokens_arr = np.array(all_tokens)
ax.hist(tokens_arr[tokens_arr < 88], bins=44, color='steelblue',
        alpha=0.8, edgecolor='white', linewidth=0.3)
ax.axvline(39, color='red', linestyle='--', label='C4 (Middle C) = Token 39')
ax.set_xlabel('Token Index (pitch)', fontsize=11)
ax.set_ylabel('Frequency', fontsize=11)
ax.set_title('Pitch Token Distribution (excl. REST)', fontsize=12)
ax.legend()

# Plot 2: Top 20 most common notes
ax2 = axes[1]
top20 = tok_counts.most_common(20)
names  = [token_to_name(t) for t, _ in top20]
counts = [c for _, c in top20]
colors = ['tomato' if n == 'REST' else 'steelblue' for n in names]
bars = ax2.bar(names, counts, color=colors, edgecolor='white')
ax2.set_xlabel('Note', fontsize=11)
ax2.set_ylabel('Count', fontsize=11)
ax2.set_title('Top 20 Most Common Tokens', fontsize=12)
ax2.tick_params(axis='x', rotation=45)

plt.tight_layout()
plt.savefig(os.path.join(CFG['EXPORT_DIR'], 'token_distribution.png'),
            dpi=150, bbox_inches='tight')
plt.show()
print('✅ Token distribution chart saved')

"""## 🔢 Section 5 — Sequence Construction & Train/Val Split

**Sliding window approach:**
```
Full token stream: [C4, E4, G4, F4, E4, D4, REST, C4, ...]

Window 1:  X = [C4, E4, G4, ...(32 tokens)]  →  y = token_33
Window 2:  X = [E4, G4, F4, ...(32 tokens)]  →  y = token_34
...
```
"""

# ── Build sliding window sequences ──────────────────────────────────

SEQ = CFG['SEQ_LEN']

X_list, y_list = [], []
for i in range(len(all_tokens) - SEQ):
    X_list.append(all_tokens[i : i + SEQ])
    y_list.append(all_tokens[i + SEQ])

X = np.array(X_list, dtype=np.int32)   # (N, 32)
y = np.array(y_list, dtype=np.int32)   # (N,)

print(f'Dataset shape:')
print(f'  X : {X.shape}  (samples × sequence_length)')
print(f'  y : {y.shape}  (target token per sample)')
print(f'  Memory: X={X.nbytes/1e6:.1f} MB  y={y.nbytes/1e6:.1f} MB')

# Train / val split (no shuffle — preserve temporal order within files)
split = int(len(X) * (1 - CFG['VAL_SPLIT']))
X_train, X_val = X[:split], X[split:]
y_train, y_val = y[:split], y[split:]

print(f'\nTrain samples : {len(X_train):,}')
print(f'Val   samples : {len(X_val):,}')

# Save vocabulary metadata
vocab_meta = {
    'vocab_size'    : CFG['VOCAB_SIZE'],
    'midi_min'      : CFG['MIDI_MIN'],
    'midi_max'      : CFG['MIDI_MAX'],
    'rest_token'    : CFG['REST_TOKEN'],
    'seq_len'       : CFG['SEQ_LEN'],
    'token_counts'  : dict(tok_counts),
    'n_train'       : len(X_train),
    'n_val'         : len(X_val),
}
with open(os.path.join(CFG['EXPORT_DIR'], 'vocab_meta.pkl'), 'wb') as f:
    pickle.dump(vocab_meta, f)

print('\n✅ Sequences built. vocab_meta.pkl saved.')

# ── Build tf.data pipelines ─────────────────────────────────────────
# Using tf.data for efficient batching with GPU prefetch

AUTOTUNE = tf.data.AUTOTUNE
BATCH    = CFG['BATCH_SIZE']

def make_dataset(X, y, shuffle=False):
    ds = tf.data.Dataset.from_tensor_slices((X, y))
    if shuffle:
        ds = ds.shuffle(buffer_size=10_000, seed=42)
    ds = ds.batch(BATCH).prefetch(AUTOTUNE)
    return ds

train_ds = make_dataset(X_train, y_train, shuffle=True)
val_ds   = make_dataset(X_val,   y_val,   shuffle=False)

print(f'Train batches : {len(train_ds)}')
print(f'Val   batches : {len(val_ds)}')
print(f'\n✅ tf.data pipelines ready with GPU prefetch')

"""## 🧠 Section 6 — Model Architectures

### Architecture Overview

| Model | Type | Can Generate? | Params | Notes |
|-------|------|:---:|--------|-------|
| **StackedLSTM** | Unidirectional | ✅ Yes | ~1.1M | Production generator |
| **StackedGRU** | Unidirectional | ✅ Yes | ~850K | Faster, comparable quality |
| **BiLSTM** | Bidirectional | ❌ No | ~2.1M | Classifier only — explains WHY |

> ⚠️ **BiLSTM cannot generate music.** During training it reads future notes (backward pass).
> During generation, future notes don't exist yet. It's kept here to demonstrate this
> concept empirically — BiLSTM gets *better* validation loss but *cannot* compose music.

"""

# ── Model factory ───────────────────────────────────────────────────

def build_stacked_lstm(name='StackedLSTM'):
    """
    Two-layer stacked LSTM.
    Autoregressive generation: ✅ YES

    Architecture:
      Input(SEQ_LEN) → Embedding(89,64) → LSTM(256, return_seq=True)
      → Dropout(0.3) → LSTM(256) → Dropout(0.3) → Dense(89)
    """
    inp       = keras.Input(shape=(CFG['SEQ_LEN'],), name='token_input')
    x         = layers.Embedding(CFG['VOCAB_SIZE'], CFG['EMBED_DIM'],
                                  name='embedding')(inp)
    # Layer 1: return_sequences=True so Layer 2 gets full seq
    x         = layers.LSTM(CFG['HIDDEN_DIM'], return_sequences=True,
                             name='lstm_1')(x)
    x         = layers.Dropout(CFG['DROPOUT'], name='drop_1')(x)
    # Layer 2: return_sequences=False — we only need last timestep
    x         = layers.LSTM(CFG['HIDDEN_DIM'], return_sequences=False,
                             name='lstm_2')(x)
    x         = layers.Dropout(CFG['DROPOUT'], name='drop_2')(x)
    out       = layers.Dense(CFG['VOCAB_SIZE'], activation='softmax',
                              name='output')(x)
    model = keras.Model(inp, out, name=name)
    return model


def build_stacked_gru(name='StackedGRU'):
    """
    Two-layer stacked GRU.
    Autoregressive generation: ✅ YES

    GRU vs LSTM:
      - GRU has 2 gates (reset, update) vs LSTM's 4 gates
      - ~22% fewer parameters
      - Trains ~25% faster per epoch
      - No separate cell state — merged into hidden state
      - Often matches LSTM for SEQ_LEN=32 (not long enough for LSTM to shine)
    """
    inp  = keras.Input(shape=(CFG['SEQ_LEN'],), name='token_input')
    x    = layers.Embedding(CFG['VOCAB_SIZE'], CFG['EMBED_DIM'],
                             name='embedding')(inp)
    x    = layers.GRU(CFG['HIDDEN_DIM'], return_sequences=True,
                      name='gru_1')(x)
    x    = layers.Dropout(CFG['DROPOUT'], name='drop_1')(x)
    x    = layers.GRU(CFG['HIDDEN_DIM'], return_sequences=False,
                      name='gru_2')(x)
    x    = layers.Dropout(CFG['DROPOUT'], name='drop_2')(x)
    out  = layers.Dense(CFG['VOCAB_SIZE'], activation='softmax',
                         name='output')(x)
    model = keras.Model(inp, out, name=name)
    return model


def build_bilstm(name='BidirectionalLSTM'):
    """
    Two-layer Bidirectional LSTM — CLASSIFIER ONLY.
    Autoregressive generation: ❌ NO

    WHY it cannot generate:
      Bidirectional runs TWO passes:
        Forward:  reads notes left → right (past context)
        Backward: reads notes right → left (FUTURE context)
      At training time, all 32 window notes are available → backward
      pass works fine. At generation time, future notes DON'T EXIST YET
      → backward pass has nothing to read → cannot run.

    The output dim doubles: 256 forward + 256 backward = 512 per layer.
    This is why it gets better val_loss than unidirectional — it's
    'cheating' by seeing the future during training.
    """
    inp  = keras.Input(shape=(CFG['SEQ_LEN'],), name='token_input')
    x    = layers.Embedding(CFG['VOCAB_SIZE'], CFG['EMBED_DIM'],
                             name='embedding')(inp)
    # Bidirectional wrapper doubles output dim: 256*2 = 512
    x    = layers.Bidirectional(
               layers.LSTM(CFG['HIDDEN_DIM'], return_sequences=True),
               name='bilstm_1')(x)
    x    = layers.Dropout(CFG['DROPOUT'], name='drop_1')(x)
    x    = layers.Bidirectional(
               layers.LSTM(CFG['HIDDEN_DIM'], return_sequences=False),
               name='bilstm_2')(x)
    x    = layers.Dropout(CFG['DROPOUT'], name='drop_2')(x)
    out  = layers.Dense(CFG['VOCAB_SIZE'], activation='softmax',
                         name='output')(x)
    model = keras.Model(inp, out, name=name)
    return model


# ── Build & compile all three ────────────────────────────────────────
models_dict = {
    'lstm'   : build_stacked_lstm(),
    'gru'    : build_stacked_gru(),
    'bilstm' : build_bilstm(),
}

optimizer_cfg = optimizers.Adam(learning_rate=CFG['LR'])

for name, model in models_dict.items():
    model.compile(
        optimizer = optimizers.Adam(learning_rate=CFG['LR']),
        loss      = 'sparse_categorical_crossentropy',
        metrics   = ['accuracy']
    )

print('Model Summary Comparison:')
print(f'{"Model":<22} {"Parameters":>12}  {"Can Generate":>14}')
print('─' * 52)
for name, m in models_dict.items():
    params = m.count_params()
    can_gen = '✅ Yes' if name != 'bilstm' else '❌ No'
    print(f'{m.name:<22} {params:>12,}  {can_gen:>14}')

print('\n✅ All 3 models compiled.')

# ── Print full architecture of LSTM (representative) ────────────────
print('=' * 60)
print('STACKED LSTM — Full Architecture')
print('=' * 60)
models_dict['lstm'].summary(line_length=60)

print('\n' + '=' * 60)
print('NOTE: BiLSTM has hidden_dim*2 in each Bidirectional layer')
print('This is why param count is ~2× the LSTM')
print('=' * 60)

"""## 🏋️ Section 7 — Training All 3 Models

**Callbacks used:**
- `ModelCheckpoint` — saves best model (val_loss)
- `EarlyStopping` — stops if val_loss doesn't improve for 8 epochs
- `ReduceLROnPlateau` — halves LR after 4 epochs no improvement
- `CSVLogger` — logs all metrics to file for post-analysis

**Expected training time on T4 GPU:** ~2-4 minutes per model (50 epochs max)

"""

# ── Training function ───────────────────────────────────────────────

history_dict = {}  # stores training history for all 3 models

def train_model(model, model_name, train_ds, val_ds):
    print(f'\n{"="*60}')
    print(f'Training: {model_name}')
    print(f'{"="*60}')

    ckpt_path = os.path.join(CFG['EXPORT_DIR'], f'{model_name}_best.keras')
    log_path  = os.path.join(CFG['EXPORT_DIR'], f'{model_name}_log.csv')

    cbs = [
        callbacks.ModelCheckpoint(
            filepath=ckpt_path,
            monitor='val_loss',
            save_best_only=True,
            verbose=0
        ),
        callbacks.EarlyStopping(
            monitor='val_loss',
            patience=CFG['PATIENCE'],
            restore_best_weights=True,
            verbose=1
        ),
        callbacks.ReduceLROnPlateau(
            monitor='val_loss',
            factor=0.5,
            patience=4,
            min_lr=1e-6,
            verbose=1
        ),
        callbacks.CSVLogger(log_path)
    ]

    history = model.fit(
        train_ds,
        epochs          = CFG['EPOCHS'],
        validation_data = val_ds,
        callbacks       = cbs,
        verbose         = 1
    )

    print(f'\n✅ {model_name} done.')
    print(f'   Best val_loss : {min(history.history["val_loss"]):.4f}')
    print(f'   Best val_acc  : {max(history.history["val_accuracy"]):.4f}')
    return history


# Train all 3 models
for model_key, model in models_dict.items():
    history_dict[model_key] = train_model(model, model_key, train_ds, val_ds)

print('\n✅ ALL 3 MODELS TRAINED SUCCESSFULLY')

# ── Plot training curves — all 3 models side by side ────────────────

fig, axes = plt.subplots(2, 3, figsize=(18, 10))
fig.suptitle('Training Curves — LSTM vs GRU vs BiLSTM', fontsize=15, fontweight='bold')

colors = {'lstm': '#2196F3', 'gru': '#4CAF50', 'bilstm': '#FF5722'}
labels = {'lstm': 'Stacked LSTM', 'gru': 'Stacked GRU', 'bilstm': 'BiLSTM (classifier)'}

for col, (model_key, hist) in enumerate(history_dict.items()):
    h     = hist.history
    color = colors[model_key]
    epochs_ran = range(1, len(h['loss']) + 1)

    # Loss
    ax = axes[0, col]
    ax.plot(epochs_ran, h['loss'],     color=color, label='Train',  linewidth=2)
    ax.plot(epochs_ran, h['val_loss'], color=color, label='Val',    linewidth=2, linestyle='--')
    ax.set_title(f'{labels[model_key]}\nLoss', fontsize=11, fontweight='bold', color=color)
    ax.set_xlabel('Epoch')
    ax.set_ylabel('Cross-Entropy Loss')
    ax.legend()
    ax.grid(True, alpha=0.3)
    best_loss = min(h['val_loss'])
    ax.axhline(best_loss, color='red', linestyle=':', alpha=0.5,
               label=f'Best: {best_loss:.3f}')
    ax.legend(fontsize=9)

    # Accuracy
    ax2 = axes[1, col]
    ax2.plot(epochs_ran, h['accuracy'],     color=color, label='Train',  linewidth=2)
    ax2.plot(epochs_ran, h['val_accuracy'], color=color, label='Val',    linewidth=2, linestyle='--')
    ax2.set_title(f'{labels[model_key]}\nAccuracy', fontsize=11, fontweight='bold', color=color)
    ax2.set_xlabel('Epoch')
    ax2.set_ylabel('Accuracy')
    best_acc = max(h['val_accuracy'])
    ax2.axhline(best_acc, color='red', linestyle=':', alpha=0.5,
                label=f'Best: {best_acc:.3f}')
    ax2.legend(fontsize=9)
    ax2.grid(True, alpha=0.3)

plt.tight_layout()
plt.savefig(os.path.join(CFG['EXPORT_DIR'], 'training_curves.png'),
            dpi=150, bbox_inches='tight')
plt.show()

# Print final comparison table
print('\n📊 FINAL MODEL COMPARISON')
print(f'{"Model":<22} {"Val Loss":>10} {"Val Acc":>10} {"Epochs":>8} {"Can Gen":>10}')
print('─' * 64)
for key, hist in history_dict.items():
    h       = hist.history
    vl      = min(h['val_loss'])
    va      = max(h['val_accuracy'])
    ep      = len(h['loss'])
    can_gen = '✅ Yes' if key != 'bilstm' else '❌ No'
    print(f'{labels[key]:<22} {vl:>10.4f} {va:>10.4f} {ep:>8} {can_gen:>10}')

print('\n⚠️  Note: BiLSTM may show lower val_loss because its backward')
print('    LSTM reads future tokens in the 32-note window (data leakage).')
print('    This is WHY it cannot be used for generation.')

"""## 💾 Section 8 — Export All Model Formats

Exports for web app deployment:

| Format | File | Use case |
|--------|------|----------|
| `.keras` | Native Keras | Full reload in Python |
| `.h5` | HDF5 | Legacy compatibility |
| `SavedModel/` | TF SavedModel | TensorFlow Serving / Cloud |
| `.tflite` | TFLite | Mobile / edge / browser |
| `weights.h5` | Weights only | Architecture-independent |
| `architecture.json` | Model JSON | Rebuild architecture |
| `vocab_meta.pkl` | Vocabulary | Token ↔ note mapping |
| `config.json` | Hyperparams | Reproducibility |

"""

# ── Export all models in all formats ────────────────────────────────

import json as json_lib

def export_model(model, model_name):
    model_dir = os.path.join(CFG['EXPORT_DIR'], model_name)
    os.makedirs(model_dir, exist_ok=True)

    print(f'\nExporting {model_name}...')

    # 1. Keras native format (.keras) — recommended
    path_keras = os.path.join(model_dir, f'{model_name}.keras')
    model.save(path_keras)
    size_kb = os.path.getsize(path_keras) / 1024
    print(f'  ✅ .keras          {size_kb:>8.1f} KB')

    # 2. HDF5 format (.h5) — legacy, widely supported
    path_h5 = os.path.join(model_dir, f'{model_name}.h5')
    model.save(path_h5)
    size_kb = os.path.getsize(path_h5) / 1024
    print(f'  ✅ .h5             {size_kb:>8.1f} KB')

    # 3. TensorFlow SavedModel format — for TF Serving / GCP / AWS
    path_saved = os.path.join(model_dir, 'saved_model')
    model.export(path_saved)
    print(f'  ✅ SavedModel/     (TF Serving ready)')

    # 4. TFLite — for mobile, edge, TensorFlow.js via converter
    try:
        converter_tfl = tf.lite.TFLiteConverter.from_keras_model(model)
        converter_tfl.optimizations = [tf.lite.Optimize.DEFAULT]
        tflite_model = converter_tfl.convert()
        path_tflite  = os.path.join(model_dir, f'{model_name}.tflite')
        with open(path_tflite, 'wb') as f:
            f.write(tflite_model)
        size_kb = os.path.getsize(path_tflite) / 1024
        print(f'  ✅ .tflite        {size_kb:>8.1f} KB  (quantized)')
    except Exception as e:
        print(f'  ⚠️  .tflite skipped: {e}')

    # 5. Weights only
    # Fix: Keras 3.x save_weights expects the filename to end precisely with `.weights.h5`.
    # Changing from `_weights.h5` to `.weights.h5` in the filename pattern.
    path_weights = os.path.join(model_dir, f'{model_name}.weights.h5')
    model.save_weights(path_weights)
    size_kb = os.path.getsize(path_weights) / 1024
    print(f'  ✅ weights.h5      {size_kb:>8.1f} KB')

    # 6. Architecture JSON
    arch_json = model.to_json()
    path_json = os.path.join(model_dir, f'{model_name}_architecture.json')
    with open(path_json, 'w') as f:
        f.write(arch_json)
    print(f'  ✅ architecture.json')

    return model_dir


# Export all 3 models
exported_dirs = {}
for key, model in models_dict.items():
    exported_dirs[key] = export_model(model, key)

# Save global config
cfg_path = os.path.join(CFG['EXPORT_DIR'], 'config.json')
with open(cfg_path, 'w') as f:
    json_lib.dump(CFG, f, indent=2)
print(f'\n✅ config.json saved')

print('\n✅ ALL EXPORTS COMPLETE')

"""## 📦 Section 9 — Package & Download Everything"""

# ── Package everything into a single ZIP ────────────────────────────

ZIP_PATH = '/content/DINRAJ_MusicRNN_Complete.zip'

print('Creating ZIP archive...')
print('Contents:')

with zipfile.ZipFile(ZIP_PATH, 'w', zipfile.ZIP_DEFLATED) as zf:
    for root, dirs, files in os.walk(CFG['EXPORT_DIR']):
        for file in files:
            full_path = os.path.join(root, file)
            arc_name  = os.path.relpath(full_path, '/content')
            zf.write(full_path, arc_name)
            size_kb = os.path.getsize(full_path) / 1024
            print(f'  + {arc_name:<65} {size_kb:>8.1f} KB')

zip_size_mb = os.path.getsize(ZIP_PATH) / (1024 * 1024)
print(f'\n✅ ZIP created: {ZIP_PATH}')
print(f'   Total size: {zip_size_mb:.2f} MB')

# ── Download the ZIP ────────────────────────────────────────────────
from google.colab import files

print('Starting download...')
files.download(ZIP_PATH)
print('✅ Download started — check your browser downloads')
print('\nZIP contains:')
print('  📁 lstm/      → .keras  .h5  SavedModel/  .tflite  weights  architecture.json')
print('  📁 gru/       → .keras  .h5  SavedModel/  .tflite  weights  architecture.json')
print('  📁 bilstm/    → .keras  .h5  SavedModel/  .tflite  weights  architecture.json')
print('  📄 vocab_meta.pkl       → token ↔ note mapping')
print('  📄 config.json          → all hyperparameters')
print('  📄 training_curves.png  → loss & accuracy plots')
print('  📄 token_distribution.png')
print('  📄 *.csv                → per-epoch training logs')

"""## 🎼 Section 10 — Music Generation

### How Autoregressive Generation Works

```
seed: [C4, E4, G4, ...(32 notes)]
         ↓
    LSTM forward pass
         ↓
    softmax → probabilities over 89 tokens
         ↓
    temperature sampling → sample next token
         ↓
    append to sequence, drop oldest
         ↓
    repeat → 200 notes generated
```

### Temperature Parameter
| Temperature | Effect | Result |
|-------------|--------|--------|
| `0.5` | Conservative | Repetitive but in-key |
| `0.8` | Balanced | Recommended |
| `1.0` | Standard softmax | More variety |
| `1.2` | Creative | Surprising, less tonal |
| `2.0` | Chaotic | Random noise |

"""

# ── Temperature sampling function ───────────────────────────────────

def sample_with_temperature(logits, temperature=0.8):
    """
    Apply temperature scaling to logits, then sample.

    Temperature formula:
        scaled_logits = log(probs) / temperature
        sample from softmax(scaled_logits)

    Low  temperature → sharper distribution → more deterministic
    High temperature → flatter distribution → more random

    Why not just argmax (greedy)?
        Greedy decoding quickly gets stuck in loops:
        C4 → E4 → G4 → C4 → E4 → G4 → ...
        Temperature adds controlled randomness that breaks loops.
    """
    if temperature == 0:
        return int(np.argmax(logits))

    logits = np.log(np.array(logits, dtype=np.float64) + 1e-10)
    logits = logits / temperature
    # Subtract max for numerical stability before exp
    logits = logits - np.max(logits)
    probs  = np.exp(logits)
    probs  = probs / np.sum(probs)
    return int(np.random.choice(len(probs), p=probs))


def generate_sequence(model, seed_tokens, length=200, temperature=0.8):
    """
    Autoregressively generate `length` new tokens.

    seed_tokens : list of SEQ_LEN integer tokens to prime the model
    Returns     : list of generated integer tokens (length = `length`)
    """
    generated  = []
    window     = list(seed_tokens[-CFG['SEQ_LEN']:])

    for step in range(length):
        # Shape: (1, SEQ_LEN)
        x     = np.array(window, dtype=np.int32).reshape(1, -1)
        probs = model.predict(x, verbose=0)[0]  # (89,) probabilities

        # Sample next token with temperature
        next_token = sample_with_temperature(probs, temperature)

        generated.append(next_token)
        window.append(next_token)
        window.pop(0)  # slide window forward

        if (step + 1) % 50 == 0:
            print(f'  Generated {step+1}/{length} tokens...', end='\r')

    print(f'  Generated {length}/{length} tokens ✅  ')
    return generated


print('✅ Generation functions ready')

# ── Choose seed from real dataset ───────────────────────────────────
# Use a real musical phrase as seed — much better than random tokens

SEED_START = np.random.randint(0, len(X_val) - 1)
seed_tokens = X_val[SEED_START].tolist()

print('Seed sequence (first 32 notes from validation set):')
seed_names = [token_to_name(t) for t in seed_tokens]
print(' → '.join(seed_names[:16]))
print(' → '.join(seed_names[16:]))

print(f'\nGenerating {CFG["GEN_LENGTH"]} notes with temperature={CFG["TEMPERATURE"]}...')

# Generate with LSTM (best generative model)
print('\n🎵 LSTM generation:')
generated_lstm = generate_sequence(
    models_dict['lstm'],
    seed_tokens,
    length      = CFG['GEN_LENGTH'],
    temperature = CFG['TEMPERATURE']
)

print('\n🎵 GRU generation:')
generated_gru = generate_sequence(
    models_dict['gru'],
    seed_tokens,
    length      = CFG['GEN_LENGTH'],
    temperature = CFG['TEMPERATURE']
)

# Show generated sequence
print('\nLSTM generated (first 32 notes):')
lstm_names = [token_to_name(t) for t in generated_lstm[:32]]
print(' → '.join(lstm_names))

# REST% — measure how musical the output is
lstm_rest_pct = 100 * generated_lstm.count(CFG['REST_TOKEN']) / len(generated_lstm)
gru_rest_pct  = 100 * generated_gru.count(CFG['REST_TOKEN'])  / len(generated_gru)
print(f'\nREST percentage → LSTM: {lstm_rest_pct:.1f}%  GRU: {gru_rest_pct:.1f}%')
print('(10-30% REST is musical; 0% = wall-to-wall notes; >50% = mostly silence)')

# ── Compare generation at different temperatures ─────────────────────

temps = [0.5, 0.8, 1.0, 1.2]

print('Temperature experiment (LSTM, 100 notes each):')
print(f'{"Temp":<8} {"Unique Notes":>14} {"REST %":>8} {"Pitch Range":>14}')
print('─' * 48)

for temp in temps:
    gen = generate_sequence(models_dict['lstm'], seed_tokens, length=100, temperature=temp)
    notes_only  = [t for t in gen if t != CFG['REST_TOKEN']]
    unique      = len(set(notes_only))
    rest_pct    = 100 * gen.count(CFG['REST_TOKEN']) / len(gen)
    if notes_only:
        pitch_range = f'{token_to_name(min(notes_only))}–{token_to_name(max(notes_only))}'
    else:
        pitch_range = 'N/A'
    print(f'{temp:<8} {unique:>14} {rest_pct:>7.1f}% {pitch_range:>14}')

print('\n💡 Higher temp = more unique notes = more creative but less structured')

"""## 🎧 Section 11 — Convert Tokens → MIDI → Audio → Play in Colab

Generated token sequence → MIDI file → WAV audio → playable in browser
"""

# ── Tokens → MIDI file ──────────────────────────────────────────────

def tokens_to_midi(tokens, output_path, tempo_bpm=120, note_duration=0.25):
    """
    Convert pitch token list → MIDI file.

    Since we used pitch-only tokenization (no duration info),
    every non-REST note gets a fixed duration of `note_duration` seconds.
    REST tokens add silence of the same duration.

    This is an inherent limitation of pitch-only representation —
    the output sounds metronomic. Adding duration tokens would fix this
    (next iteration of the model).

    Args:
        tokens       : list of int token indices
        output_path  : path to save .mid file
        tempo_bpm    : beats per minute
        note_duration: seconds per note (uniform)
    """
    midi = pretty_midi.PrettyMIDI(initial_tempo=tempo_bpm)
    piano = pretty_midi.Instrument(
        program=pretty_midi.instrument_name_to_program('Acoustic Grand Piano')
    )

    current_time = 0.0

    for token in tokens:
        if token == CFG['REST_TOKEN']:
            # REST: advance time, no note
            current_time += note_duration
        else:
            midi_pitch = token_to_pitch(token)
            # Clip to valid MIDI range just in case
            midi_pitch = max(0, min(127, midi_pitch))

            note_on  = current_time
            note_off = current_time + note_duration * 0.9  # 10% gap between notes

            note_obj = pretty_midi.Note(
                velocity  = 80,
                pitch     = midi_pitch,
                start     = note_on,
                end       = note_off
            )
            piano.notes.append(note_obj)
            current_time += note_duration

    midi.instruments.append(piano)
    midi.write(output_path)
    duration = current_time
    return duration


# ── Export both LSTM and GRU generated music as MIDI ────────────────
for model_key, gen_tokens in [('lstm', generated_lstm), ('gru', generated_gru)]:
    midi_path = f'/content/generated_{model_key}.mid'
    duration  = tokens_to_midi(gen_tokens, midi_path, tempo_bpm=120)
    size_kb   = os.path.getsize(midi_path) / 1024
    print(f'✅ {model_key.upper()} MIDI: {midi_path}')
    print(f'   Duration : {duration:.1f} seconds  |  Size: {size_kb:.1f} KB')

# Copy to export dir
shutil.copy('/content/generated_lstm.mid', CFG['EXPORT_DIR'])
shutil.copy('/content/generated_gru.mid',  CFG['EXPORT_DIR'])
print('\n✅ MIDI files saved and copied to export directory')

# ── Convert MIDI → WAV → Play in Colab ──────────────────────────────
# Uses FluidSynth (installed in Section 1) with a soundfont

import subprocess

def download_soundfont():
    """Download a free GM soundfont for MIDI rendering."""
    sf_path = '/content/soundfont.sf2'
    if not os.path.exists(sf_path):
        print('Downloading soundfont...')
        !wget -q -O /content/soundfont.sf2 \
            'https://freepats.zenvoid.org/Piano/UprightPianoKW-SF2-20220221.tar.gz' 2>/dev/null || \
        !apt-get install -qq fluid-soundfont-gm && cp /usr/share/sounds/sf2/FluidR3_GM.sf2 /content/soundfont.sf2
    return sf_path

def midi_to_wav(midi_path, wav_path, sf_path='/content/soundfont.sf2'):
    """Use FluidSynth to render MIDI → WAV."""
    cmd = ['fluidsynth', '-ni', sf_path, midi_path,
           '-F', wav_path, '-r', '22050']
    result = subprocess.run(cmd, capture_output=True, text=True)
    return result.returncode == 0


# Try to get soundfont and render audio
try:
    # Try system soundfont first
    sf_candidates = [
        '/usr/share/sounds/sf2/FluidR3_GM.sf2',
        '/usr/share/sounds/sf2/fluid-soundfont-gm.sf2',
        '/content/soundfont.sf2'
    ]
    sf_path = next((p for p in sf_candidates if os.path.exists(p)), None)

    if sf_path is None:
        print('Installing soundfont...')
        subprocess.run(['apt-get', 'install', '-qq', '-y', 'fluid-soundfont-gm'],
                       capture_output=True)
        sf_path = '/usr/share/sounds/sf2/FluidR3_GM.sf2'

    print(f'Using soundfont: {sf_path}')

    # Render LSTM output
    wav_lstm = '/content/generated_lstm.wav'
    success  = midi_to_wav('/content/generated_lstm.mid', wav_lstm, sf_path)

    if success and os.path.exists(wav_lstm):
        print('\n🎵 LSTM Generated Music — Play below:')
        display(Audio(wav_lstm, autoplay=False))
        shutil.copy(wav_lstm, CFG['EXPORT_DIR'])

        # Render GRU output
        wav_gru = '/content/generated_gru.wav'
        midi_to_wav('/content/generated_gru.mid', wav_gru, sf_path)
        if os.path.exists(wav_gru):
            print('\n🎵 GRU Generated Music — Play below:')
            display(Audio(wav_gru, autoplay=False))
            shutil.copy(wav_gru, CFG['EXPORT_DIR'])
    else:
        print('⚠️  FluidSynth rendering failed — MIDI files are still usable')
        print('    Open the .mid files in GarageBand, MuseScore, or any DAW')

except Exception as e:
    print(f'⚠️  Audio rendering error: {e}')
    print('   MIDI files are saved — open them in any MIDI player or DAW')

# ── Visualise the generated piano roll ──────────────────────────────

def plot_piano_roll(tokens, title, ax, max_notes=100):
    """Plot pitch tokens as a piano roll."""
    tokens_vis = tokens[:max_notes]
    pitches    = []
    positions  = []

    for i, t in enumerate(tokens_vis):
        if t != CFG['REST_TOKEN']:
            pitches.append(token_to_pitch(t))
            positions.append(i)

    ax.scatter(positions, pitches, s=25, c=pitches,
               cmap='plasma', alpha=0.8, zorder=3)
    ax.plot(positions, pitches, alpha=0.3, color='gray', linewidth=0.8)

    # Mark octave boundaries
    for octave in range(2, 8):
        ax.axhline(octave * 12, color='lightblue', alpha=0.3, linewidth=0.5)

    ax.set_ylabel('MIDI Pitch')
    ax.set_xlabel('Note Position')
    ax.set_title(title, fontweight='bold')
    ax.set_ylim(30, 100)
    ax.grid(True, alpha=0.2)

    # Add note name labels on y-axis
    yticks = [36, 48, 60, 72, 84]
    ylabels = ['C2', 'C3', 'C4\n(Middle)', 'C5', 'C6']
    ax.set_yticks(yticks)
    ax.set_yticklabels(ylabels, fontsize=8)


fig, axes = plt.subplots(3, 1, figsize=(18, 12))
fig.suptitle('Piano Roll Visualisation — Generated Music', fontsize=14, fontweight='bold')

plot_piano_roll(seed_tokens,    'Seed Sequence (Real Music — Input)',     axes[0])
plot_piano_roll(generated_lstm, 'LSTM Generated Melody (200 notes)',      axes[1])
plot_piano_roll(generated_gru,  'GRU Generated Melody (200 notes)',       axes[2])

plt.tight_layout()
plt.savefig(os.path.join(CFG['EXPORT_DIR'], 'piano_roll.png'),
            dpi=150, bbox_inches='tight')
plt.show()
print('✅ Piano roll saved')

"""## 📝 Section 13 — Limitations & What Transformers Solve

This section is for your README, blog post, and interview answers.

### What This RNN Model Does Well
- Learns **local melodic patterns** (which note likely follows which)
- Generates sequences that are **tonally plausible** (stays roughly in-key)
- **Fast to train** — 50 epochs in minutes on T4
- **Small model** (~1M params) — can run on CPU in a web app

### Fundamental Limitations of RNN Music Models

| Problem | What Happens | Why |
|---------|-------------|-----|
| **Long-term structure** | No repeated themes, no verse/chorus | LSTM hidden state can't compress 200+ notes |
| **Repetition loops** | Same 4-note phrase repeats forever | High-prob cycles dominate at low temperature |
| **No hierarchy** | Can't distinguish bar vs phrase vs section | Flat token sequence = no structural tokens |
| **Pitch-only** | Rhythm sounds mechanical | Duration not in vocabulary |
| **No harmony** | Single melody, no chords | Chord modeling needs simultaneous tokens |

### How Transformers (Music Transformer, MusicGen) Solve These

```
RNN:          token_t = f(token_{t-1}, hidden_{t-1})
              ↑ can only look back through a compressed vector

Transformer:  token_t = attention(token_t, ALL previous tokens)
              ↑ direct attention to any past position
              ↑ bar 1 theme can directly influence bar 32
              ↑ relative position embeddings encode musical timing
```

**Your next project upgrade path:**
1. Add duration tokens → rhythmically expressive output
2. Replace LSTM with small Transformer decoder → long-range structure  
3. Add instrument conditioning → generate for specific instruments
4. Fine-tune on genre-specific data → stylistic control

---

> **Portfolio Note:** The fact that you can articulate *why* RNNs fail at global
> musical structure — and explain how attention mechanisms fix it — demonstrates
> the kind of architectural understanding that ₹25L+ AI roles test for.

"""